version: '2'
services:
    tele-app:
        image: tele
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_COUCHBASE_BOOTSTRAP_HOSTS=tele-couchbase
            - SPRING_COUCHBASE_BUCKET_NAME=tele
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    tele-couchbase:
        extends:
            file: couchbase.yml
            service: tele-couchbase
